config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Micropost App with Rails7 by 
    <a href="https://github.com/tomoyuki65/rt-c2207" target="_blank" rel="noopener">
      Tomoyuki
    </a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <%= link_to "RT-C2207 App", root_path, id: "logo" %>
    <nav>
      <ul class="navbar navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path  %></li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink"
               role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
              <li><%= link_to "Profile", current_user, class: "dropdown-item" %></li>
              <li><%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= button_to "Log out", logout_path, method: :delete, class: "dropdown-item" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_not_logged_in.html.erb
<div class="not_logged_in_margin"></div>
<div class="not_logged_in bg-light p-4 p-sm-5 my-4 rounded">
  <div class="sign_up">
    <p>Micropost App with Rails7 を始めよう</p>
    <%= link_to "メールアドレスで登録", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
  <div class="log_in">
    <p>アカウントをお持ちの場合</p>
    <%= link_to "ログイン", login_path, class: "btn btn-lg btn-outline-secondary" %>
    <div class="guest-id-pass">
      <p>▼ ゲストユーザー用のログインIDとパスワードはこちら ▼</p>
      <% if Rails.env.production? %>
        <div class="id-pass">
          ログインID：guest@example.com<br>
          パスワード：guest08
        </div>
      <% else %>
        <div class="id-pass">
          ログインID：guest@example.com<br>
          パスワード：guestpass
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_rails_default.html.erb
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html15.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <% unless logged_in? %>
        <%= render "layouts/not_logged_in" %>
      <% end %>
      <%= render "layouts/footer" %>
      <%= debug(params.to_yaml) if Rails.env.development? %>
    </div>
  </body>
</html>